name: PHP setup
on: [push]
jobs: 
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug
        tools: php-cs-fixer, phpunit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
