name: PHP setup
on: [push]
jobs: 
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug
        tools: php-cs-fixer, phpunit, phpstan, psalm, phpcs, cs2pr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - run: |
                composer install # install your apps dependencies
                composer require staabm/annotate-pull-request-from-checkstyle # install cs2pr
                vendor/bin/phpstan analyse --error-format=checkstyle | vendor/bin/cs2pr
                
    #- name: Setup problem matchers for php
    #  run: echo "::add-matcher::${{ runner.tool_cache}}/php.json"
    #- name: Setup problem matchers for PHPUnit
    #  run: echo "::add-matcher::${{ runner.tool_cache}}/phpunit.json"
    #- name: Setup problem matchers for PHPStan
    #  run: phpstan analyse src
    #- name: Setup problem matchers for Psalm
    #  run: psalm --output-format=github
    #- name: PHP Coding Standards Fixer
    #  run: php-cs-fixer fix --dry-run --format=checkstyle | cs2pr
    #- name: Run PHPCS
    #  run: phpcs --report=checkstyle -q /path/to/code | cs2pr
    #- name: Check PHP code style
    #  id: phpcs
    #  run: phpcs --report-full --report-checkstyle=./phpcs-report.xml
    #- name: Show PHPCS results in PR
    #  if: ${{ always() && steps.phpcs.outcome == 'failure' }}
    #  run: cs2pr ./phpcs-report.xml
